"""
This is a setup.py script generated by py2applet. Make sure NOT to use a Conda Python interpreter when using
this script to create the .app!

Usage:
    python setup.py py2app
"""

from setuptools import setup

from main import APP_NAME, APP_VERSION

APP = ['main.py']
DATA_FILES = ["resources"]
OPTIONS = {'iconfile': 'resources/bmc.icns', }

setup(
    name=APP_NAME,
    version=APP_VERSION,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', "PyYAML"],
)
